version: '3'
services: 
    web:
        build:
            dockerfile: Dockerfile
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server/:/app
    nginx:
        image: nginx
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/:/etc/nginx/certs
        depends_on: 
            - "web"
        restart: always
        ports: 
            - '3000:443'
            # - '3000:80'

